name: Expo Master - Build

on:
 push:
   branches:
     - main
jobs:
  build:
     name: Build
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v2
     - name: Use Node.js ${{ matrix.node-version }}
       uses: actions/setup-node@v1
       with:
        node-version: 14.x
     - uses: expo/expo-github-action@v5
       with:
        expo-version: 4.x
        expo-username: ${{ secrets.EXPO_CLI_USERNAME }}
        expo-password: ${{ secrets.EXPO_CLI_PASSWORD }}
        expo-cache: true
        expo-packager: npm
     - name: Install dependencies
        
       run: npm install
        
     - name: Builds
       run: npx eas-cli build --platform all --non-interactive
 
